### ISSUE TITLE
Custom data에 LLFF를 실행 하는 경우 오류가 발생함

### ISSUE THREAD

**Issue by Songinpyo** [ProtossDragoon/PlankHyundong#20]
### 문제상황
'/content/drive/MyDrive/dev/llff_data/hyundong360/images'
경로에 sampling한 50개의 이미지를 넣어놓고 colmap을 실행시켰습니다.

```
/content/LLFF
Need to run COLMAP
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/content/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/content/drive/MyDrive/dev/llff_data/hyundong360/database.db', '--image_path', '/content/drive/MyDrive/dev/llff_data/hyundong360/images', '--ImageReader.single_camera', '1']' returned non-zero exit status 1.
```

### 스크린샷 등 시각자료
![image](https://user-images.githubusercontent.com/104220612/203501351-c72db5c1-9236-4eb9-ae18-d59ff83d4227.png)

**Comment by ProtossDragoon** [comment]
안녕하세요 인표님, 해당 이슈는 LLFF 이 내부적으로 COLMAP 을 호출하는데, 빌드된 COLMAP 버전이 최근부터 https://github.com/colmap/colmap/issues/967 이나 https://github.com/colmap/colmap/issues/1324 에서 보고된 바와 같이 x11 forwarding 을 사용하도록 요구하는 것으로 보입니다. 

저희 팀이 제공하는 COLAB 노트북에서 설치하는 COLMAP 버전이 고정되어 있지 않아 생긴 문제이기 때문에, 적절한 버전 확인한 뒤에 노트북과 이슈 업데이트해 드리겠습니다. 사용에 불편 드려 죄송합니다!

**Comment by yyongjae** [comment]
#22

**Comment by ProtossDragoon** [comment]
추가 이슈 있으시면 편히 말씀주세요!
